### ISSUE TITLE
If the file has a large error report (circa 1500 errors), the report gets truncated and does not display all

### ISSUE THREAD

**Issue by gabriel403** [benmatselby/atom-php-checkstyle#16]
As in this screenshot, it only shows for the first ~1k lines of code
![screenshot 2014-03-11 21 11 36](https://f.cloud.github.com/assets/118638/2391034/e3bb6d80-a961-11e3-9485-0d4f162df058.png)

**Comment by benmatselby** [comment]
Closing this issue down, as it's been nearly a decade, and I'm going to archive the repo.
