### ISSUE TITLE
Getting exception 'UnexpectedValueException' upon running phpcs

### ISSUE THREAD

**Issue by jegtnes** [benmatselby/atom-php-checkstyle#19]
Hey there,

I've installed this package and set the right executable paths for phpcs, phpcsfixer, and phpmd. All of these have been installed with Homebrew.

Phpmd works, but when enabling phpcs I get an error every time the package runs. Looking at Atom's console, running the same command in Terminal results in the following UnexpectedValueExceptions:

``` php
/usr/local/bin/php -l -d display_errors=On /Path/to/File.php; /usr/local/bin/phpcs --standard=PSR2 --report=checkstyle /Path/to/File.php; /usr/local/bin/phpmd /Path/to/File.php text codesize,cleancode,controversial,naming,unusedcode;  
No syntax errors detected in /Path/to/File.php
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'DirectoryIterator::__construct(/usr/local/etc/php-code-sniffer/Standards): failed to open dir: No such file or directory' in /usr/local/Cellar/php-code-sniffer/1.5.2/CodeSniffer.php:1961
Stack trace:
#0 /usr/local/Cellar/php-code-sniffer/1.5.2/CodeSniffer.php(1961): DirectoryIterator->__construct('/usr/local/etc/...')
#1 /usr/local/Cellar/php-code-sniffer/1.5.2/CodeSniffer/CLI.php(733): PHP_CodeSniffer::getInstalledStandards()
#2 /usr/local/Cellar/php-code-sniffer/1.5.2/CodeSniffer/CLI.php(538): PHP_CodeSniffer_CLI->validateStandard(Array)
#3 /usr/local/Cellar/php-code-sniffer/1.5.2/scripts/phpcs(37): PHP_CodeSniffer_CLI->process()
#4 {main}
  thrown in /usr/local/Cellar/php-code-sniffer/1.5.2/CodeSniffer.php on line 1961

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'DirectoryIterator::__construct(/usr/local/etc/php-code-sniffer/Standards): failed to open dir: No such file or directory' in /usr/local/Cellar/php-code-sniffer/1.5.2/CodeSniffer.php:1961
Stack trace:
#0 /usr/local/Cellar/php-code-sniffer/1.5.2/CodeSniffer.php(1961): DirectoryIterator->__construct('/usr/local/etc/...')
#1 /usr/local/Cellar/php-code-sniffer/1.5.2/CodeSniffer/CLI.php(733): PHP_CodeSniffer::getInstalledStandards()
#2 /usr/local/Cellar/php-code-sniffer/1.5.2/CodeSniffer/CLI.php(538): PHP_CodeSniffer_CLI->validateStandard(Array)
#3 /usr/local/Cellar/php-code-sniffer/1.5.2/scripts/phpcs(37): PHP_CodeSniffer_CLI->process()
#4 {main}
  thrown in /usr/local/Cellar/php-code-sniffer/1.5.2/CodeSniffer.php on line 1961
```

Isolating the error to the command `/usr/local/bin/phpcs  --report=checkstyle --standard=PSR2 /Path/to/File.php` I attempted to remove and tweak the parameters, and it seems the error is thrown by the '--standard=PSR2' flag. By removing this in the Terminal it works and returns warnings about my code.

I'm not too familiar with PHPCS, so this might not be an issue related to the package, and if it's not—my apologies. :) A quick pointer in the right direction would be fabulous, though. Thanks!

**Comment by corysimmons** [comment]
I'm getting this too.

I installed phpcs with brew, and WPCS via the "To Summarize" section https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards#standalone

I ran `phpcs --config-set installed_paths wpcs` to link them, and now I can't even run `php -i` without it throwing an error that the WP standard isn't in the Cellar dir...

```
PHP Fatal error:  Uncaught UnexpectedValueException: DirectoryIterator::__construct(/Users/corysimmons/wpcs): failed to open dir: No such file or directory in /usr/local/Cellar/php-code-sniffer/2.7.1/CodeSniffer.php:2250
```

Any ideas? I suspect it has something to do with brew.

**Comment by Manassoft** [comment]
![untitled](https://cloud.githubusercontent.com/assets/28344365/25655788/cf5c18d0-3013-11e7-8659-312bf3157a6f.png)

**Comment by hvsharma63** [comment]
I'm getting the error similar to this 
phpcs: Uncaught UnexpectedValueException: DirectoryIterator::__construct(vendor/wimg/php-compatibility,vendor/wimg/php-compatibility): The system cannot find the path specified. (code: 3) in C:\Users\HAX63\AppData\Roaming\Composer\vendor\squizlabs\php_codesniffer\src\Util\Standards.php:93
in Visual Studio Code.
Help if you've any solution

**Comment by hvsharma63** [comment]
I'm getting the error similar to this
`phpcs: Uncaught UnexpectedValueException: DirectoryIterator::__construct(vendor/wimg/php-compatibility,vendor/wimg/php-compatibility): The system cannot find the path specified. (code: 3) in C:\Users\HAX63\AppData\Roaming\Composer\vendor\squizlabs\php_codesniffer\src\Util\Standards.php:93`
in Visual Studio Code.
Help if you've any solution

**Comment by benmatselby** [comment]
Hi @hvsharma63 

I'm no longer maintaining this plugin as I do not use Atom any more.. I believe https://github.com/atomlinter may be of interest to you

**Comment by hvsharma63** [comment]
Okay. 👍
