### ISSUE TITLE
Poor colour contrast makes it really hard to read the list view.

### ISSUE THREAD

**Issue by valorin** [benmatselby/atom-php-checkstyle#25]
Not sure if this is an issue with this package, or atom in general, but with the default Atom Dark theme, the poor colour contrast in the list view makes it really hard to read anything.

![screenshot from 2014-06-16 21 17 03](https://cloud.githubusercontent.com/assets/897369/3286391/11d7c2cc-f548-11e3-99bd-52891af5fb9c.png)

Happy to change custom atom stylesheet, if that's the best solution... I don't have a clue how though, but happy to follow instructions :-)

**Comment by benmatselby** [comment]
Closing this issue down, as it's been nearly a decade, and I'm going to archive the repo.
