### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by gambledor** [benmatselby/atom-php-checkstyle#31]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
PhpCheckstyleStatusBarView.initialize (/Users/giuseppelobrutto/.atom/packages/php-checkstyle/lib/php-checkstyle-statusbar-view.coffee:15:22)
```

**Comment by benmatselby** [comment]
As per the Readme I'm no longer supporting this plugin as AtomLinter provides all of the functionality this plugin was offering. Apologies
